CREATE TABLE users (
	id           BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username     VARCHAR(255)    UNIQUE,
	password     VARCHAR(255),
	role         VARCHAR(255),
  created_at   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
